version: "3.1"

services:
  db:
    image: postgres:15.2-alpine3.17
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: flowershop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  minio:
    image: minio/minio:RELEASE.2023-04-28T18-11-17Z
    restart: always
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    ports:
      - 9000:9000
      - 9001:9001
    command: "server /data --console-address \":9001\""
